#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATING A CONFIGURATION
#=================================================
ynh_script_progression "Updating the configuration file..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# RUN DB MIGRATION
#=================================================
ynh_script_progression "Running DB initial migration..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app $nodejs_dir/yarn db:migrate
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# SLACK WARNING
#=================================================
ynh_print_info "Don't forget to add a new redirction URL in your Slack app settings !"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
